import { useState, useRef, useEffect } from 'react';
import ChatInterface from './ChatInterface';
import { UserProfile, AppConfig } from '../types';
import { Download, CheckCircle2 } from 'lucide-react';
import JSZip from 'jszip';
import { toast } from 'react-hot-toast';
import { motion, AnimatePresence } from 'motion/react';

interface WebBuilderProps {
  profile: UserProfile | null;
  config: AppConfig | null;
  conversationId?: string | null;
  onConversationCreated?: (id: string) => void;
}

export default function WebBuilder({ profile, config, conversationId, onConversationCreated }: WebBuilderProps) {
  const [lastResponse, setLastResponse] = useState('');
  const [showSuccess, setShowSuccess] = useState(false);

  const handleDownloadZip = async () => {
    // In a real app, we'd extract code blocks more precisely
    // For this demo, we'll look for markdown code blocks
    const codeBlocks = lastResponse.match(/```(?:[a-z]*)\n([\s\S]*?)```/g);
    
    if (!codeBlocks) {
      toast.error('No code blocks found to export.');
      return;
    }

    const zip = new JSZip();
    codeBlocks.forEach((block, index) => {
      const code = block.replace(/```(?:[a-z]*)\n/g, '').replace(/```/g, '');
      const lines = block.split('\n');
      const lang = lines[0].replace('```', '') || 'txt';
      
      // Try to guess filename from content or just use index
      let filename = `source_${index + 1}.${lang === 'javascript' ? 'js' : lang === 'typescript' ? 'ts' : lang === 'html' ? 'html' : lang === 'css' ? 'css' : 'txt'}`;
      
      zip.file(filename, code);
    });

    zip.file('README.txt', 'Generated by TrueOnce WebBuilder AI.');

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trueonce_project_${Date.now()}.zip`;
    a.click();
    window.URL.revokeObjectURL(url);

    setShowSuccess(true);
    setTimeout(() => setShowSuccess(false), 5000);
  };

  return (
    <div className="h-full relative flex flex-col">
      <div className="absolute top-2 right-2 md:top-4 md:right-4 z-20 flex gap-2">
        <button
          onClick={handleDownloadZip}
          className="flex items-center gap-2 bg-orange-500 hover:bg-orange-600 text-white px-3 py-1.5 md:px-4 md:py-2 rounded-full font-bold text-[10px] md:text-sm shadow-xl transition-all"
        >
          <Download size={14} className="md:w-4 md:h-4" />
          Export ZIP
        </button>
      </div>

      <div className="flex-1 overflow-hidden">
        <ChatInterface 
          profile={profile} 
          config={config} 
          useWebBuilder={true} 
          conversationId={conversationId}
          onConversationCreated={onConversationCreated}
          onResponse={setLastResponse}
        />
      </div>

      <AnimatePresence>
        {showSuccess && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="absolute bottom-24 left-1/2 -translate-x-1/2 bg-green-500 text-white px-6 py-4 rounded-3xl shadow-2xl flex items-center gap-3 z-50 pointer-events-none"
          >
            <div className="bg-white/20 p-2 rounded-full">
              <CheckCircle2 size={24} />
            </div>
            <div>
              <p className="font-bold">Project Ready!</p>
              <p className="text-xs opacity-90">ZIP file has been generated and downloaded.</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
